### ISSUE TITLE
Raw php Data with delete request

### ISSUE THREAD

**Issue by dchankhour2** [Mashape/unirest-php#92]
Hi,

When i call the http delete request with multiple parameters, i'm receiving the request on the other end as raw POST:

------------------------------4a8b2889f9f5
Content-Disposition: form-data; name="amount"

0.25

This does not happen when calling the post method.

I have tried updating the headers to be:

$headers = array(
		"Accept" => "application/json",
		"Content-type" => "application/x-www-form-urlencoded"
	);

But the issue still happens.

Any thought on the issue?

**Comment by ahmadnassri** [comment]
Hey @dchankhour2 i'm not certain what the issue here is, best to use mockbin.org and create a bin with some example calls so I can visualize and have a repeatable test.

thanks.

**Comment by dchankhour2** [comment]
The following is the code that i use:

`$data = array(
		'amount' => $giving['Amount'],
		'previousTransactionNumber' => $giving['AuthorizationCode'],
		'authorizationCode' => $giving['TransID']
	);

	require_once $_SERVER['DOCUMENT_ROOT'] . '/admin/plugins/unirest/Unirest.php';
	$headers = array("Accept" => "application/json");
	Unirest\Request::auth($set['accounting_username'], $set['accounting_password'], CURLAUTH_DIGEST);
	$response = Unirest\Request::delete($_accounting_api_url . 'payments', $headers, $data);`


When i try to read the $_POST, on the other end, i'm getting the post as raw data, and not a post array.
This does not happen when i do a post ::post call.

If that does not help, i can try to use mockbin.org to show some examples.

**Comment by ahmadnassri** [comment]
Unirest **does not** automatically set the `Content-Type` header
  - so your server is *automatically assuming* either a `application/x-www-form-urlencoded` or a `multipart/form-data` content type for `POST` requests
  - hence why `POST` just works out of the box
  - which is a dangerous assumption, you should probably check on that
  - you should manually set the `Content-Type` header for `DELETE` requests , but that does not guarantee that you'll get the values populated into `$_POST`, depending on your framework/setup you might still have to manually parse the raw body into that.

**Comment by ahmadnassri** [comment]
I suggest trying to send the same request to `mockbin.org/request` or better yet, [create a bin](http://mockbin.com/bin/create) then inspect what is being sent

**Comment by ahmadnassri** [comment]
this is now fixed in [`v3.0.0`][release]

**PLEASE NOTE**: `v3.0.0` introduces API changes, please review the [release notes][release] and [README](https://github.com/Mashape/unirest-php/blob/master/README.md) for details

[release]: https://github.com/Mashape/unirest-php/releases/tag/v3.0.0

**Comment by dchankhour2** [comment]
I have upgraded to v 3.0.1 but the issue still happens.  I'm able to call the same end point with same input parameters from a different framework and i don't get the result.

@ahmadnassri  I'm not clear on what how to utilize mockbin.org/request to help with this situation,  can you please explain what you would like me to try.
